version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
    commands:
      - echo "Installing dependencies..."
      - dotnet restore || (echo "dotnet restore failed" && exit 1)

  build:
    commands:
      - echo "Building the .NET application..."
      - dotnet build --configuration Release || (echo "dotnet build failed" && exit 1)

  post_build:
    commands:
      - echo "Creating output directory..."
      - mkdir -p ./output
      - echo "Publishing the .NET application..."
      - dotnet publish --configuration Release --output ./output || (echo "dotnet publish failed" && exit 1)
      - echo "Packaging the application as a ZIP file..."
      - zip -r output.zip ./output || (echo "ZIP creation failed" && exit 1)

artifacts:
  files:
    - output.zip
    - appspec.yml

cache:
  paths:
    - /root/.nuget/packages/**/*
